apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "cronhealth.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  POLL_INTERVAL_SECONDS: {{ .Values.config.pollIntervalSeconds | quote }}
  ALERT_COOLDOWN_MINUTES: {{ .Values.config.alertCooldownMinutes | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  AWS_SNS_SMS_ENABLED: {{ .Values.config.awsSnsSmsEnabled | quote }}
